apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust
    role: master
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: web
    port: 8089
    targetPort: 8089
  - protocol: TCP
    name: worker-p1
    port: 5557
    targetPort: 5557
  - protocol: TCP
    name: worker-p2
    port: 5558
    targetPort: 5558
  selector:
    name: locust
    role: master
