apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - client
      containers:
        - name: locust
          image: unicell/locust:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: http://172.20.2.110
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
